name: E2E on Chrome
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
